### ISSUE TITLE
Cose da fare

### ISSUE THREAD

**Issue by lmarchetti02** [andrea-orione/scacchi-TCF#13]
- Rimuovere funzioni non utilizzate

**Comment by andrea-orione** [comment]
Fatto un check di tutte le funzioni per le varie classi.
- Coordinate e Movement:
  I setter non vengono mai usati. Si possono anche togliere, tanto creiamo tutto già con i valori che ci interessano
- BoardFactory:
  LoadBoardPosition() si può mettere privata
- GameManager:
  GameLoop() is può mettere privata
- BoardRenderer:
  Si può mettere tutto protected tranne la printBoard(PieceColor)
