### ISSUE TITLE
Funzioni

### ISSUE THREAD

**Issue by lmarchetti02** [andrea-orione/scacchi-TCF#31]
Controllare se alcune funzioni pubbliche delle classi possono diventare provate/protette.

Poi metterei la Board come child del GameManager, così spostiamo la funzione makePiece in proteced.

**Comment by andrea-orione** [comment]
Per la board come child eviterei.
Primo perché se teniamo la singleton almeno vede che abbiamo letto.
Poi concettualmente la board e il gamemanager sono cose diverse, non uno la generalizzazione dell'altra.
Quello che proporrei è spostare makePiece dentro la board.
Ne possiamo parlare poi sabato 5 minuti

Per le funzioni private poi do un'occhiata
