### ISSUE TITLE
Colored board bug

### ISSUE THREAD

**Issue by lmarchetti02** [andrea-orione/scacchi-TCF#39]
Bisogna cambiare il colore del foreground, altrimenti i pezzi bianchi diventano neri e viceversa. È una cagata, penso.

**Comment by andrea-orione** [comment]
Bisogna prendere in considerazione il caso in cui il prof abbia il terminale con il background bianco, in tal caso i colori vengono al contrario.

**Comment by lmarchetti02** [comment]
Allora poi ci penso
