### ISSUE TITLE
Make add funcion of  Coordinate as a friend function of the Moovement

### ISSUE THREAD

**Issue by andrea-orione** [andrea-orione/scacchi-TCF#5]
Dato che non posso toccare il codice, lo scrivo qui così non mi dimentico.
Il prof fa notare che se fai overloading di un operatore (e.g. +) che prenda due tipi diversi (TypeA + TypeB), questo va dichiarato nella classe TypeA (questo l'ho già fatto) ma bisogna anche mettere l'overloading come friend function di TypeB per accedere ai suoi attributi.
Nel nostro caso (TypeA = Coordinte e TypeB = Movement) io non l'ho fatto, perché ho usato i getter di Movement. Ma direi di fare come dice lui, per dare almeno l'apparenza di seguire

**Comment by lmarchetti02** [comment]
ma vai a cagare.

Paolo

**Comment by lmarchetti02** [comment]
È più elegante con i getter.
